[book]
title = "넷평의 미디어 노트"
description = "note.mediamix"
authors = ["netpyoung"]
language = "ko"
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
additional-css = ["custom.css"]
no-section-label = true
site-url = "/note.mediamix/"
git-repository-url = "https://github.com/netpyoung/note.mediamix"
edit-url-template = "https://github.com/netpyoung/note.mediamix/edit/main/{path}"
